#!/usr/bin/env bash
#===============================================================================
# TEMPLATE — does not parse until you replace <APPLIANCE-*> placeholders
# AND rename this file (the filename itself contains a placeholder).
# The angle-bracket placeholders look like I/O redirection to bash, so
# `bash -n` will fail on the unfilled template.
#===============================================================================
# <APPLIANCE-SHORT>-sconfig — <APPLIANCE-TITLE> Configuration Tool
#
# Whiptail TUI plus headless CLI. Handles deployment configuration and
# management of <APPLIANCE-TITLE> on Debian 13 (Trixie).
#
# Usage:
#   sudo <APPLIANCE-SHORT>-sconfig                   # interactive TUI
#   sudo <APPLIANCE-SHORT>-sconfig --status          # one-shot summary
#   sudo <APPLIANCE-SHORT>-sconfig --help            # full headless CLI docs
#
# Maintainer notes (per STYLE.md §8):
#   - TUI menu functions collect input and confirm destructive operations.
#   - Shared helpers do the real work and are also called by the headless
#     CLI dispatcher at the bottom of this file.
#   - Keep deployment-specific decisions out of prepare-image.sh.
#   - Read STYLE.md §15 before writing any operator-facing text. Boring
#     system-admin language for anything that ends up in front of an
#     operator's eye; the "custom appliance" framing is for builders.
#===============================================================================
# Note: relaxed to set -uo (no -e) because whiptail returns non-zero on
# Cancel and we check exit codes locally.
set -uo pipefail

readonly VERSION="0.1.0"
readonly SCRIPT_NAME="<APPLIANCE-SHORT>-sconfig"
readonly WT_HEIGHT=22
readonly WT_WIDTH=78
readonly WT_MENU_HEIGHT=14

readonly STATE_DIR="/var/lib/<APPLIANCE-SHORT>"
readonly DEPLOY_FILE="${STATE_DIR}/deploy.env"

#===============================================================================
# APPLIANCE-CORE LIB SOURCING
#
# prepare-image.sh vendors the appliance-core libs into the canonical
# /usr/local/lib/appliance-core/ at build time. Sentinel-guarded sourcing
# here means an older image that's missing one of the libs degrades
# gracefully (the lib's functions stay undefined and consumers fall back
# to inline behavior) instead of hard-failing at startup.
#===============================================================================
readonly APPCORE_LIBS="/usr/local/lib/appliance-core"
if [[ -d "$APPCORE_LIBS" ]]; then
    [[ -f "$APPCORE_LIBS/identity.sh"  ]] && source "$APPCORE_LIBS/identity.sh"
    [[ -f "$APPCORE_LIBS/tui.sh"       ]] && source "$APPCORE_LIBS/tui.sh"
    [[ -f "$APPCORE_LIBS/hostname.sh"  ]] && source "$APPCORE_LIBS/hostname.sh"
    [[ -f "$APPCORE_LIBS/detect-net.sh" ]] && source "$APPCORE_LIBS/detect-net.sh"
    [[ -f "$APPCORE_LIBS/apt-helpers.sh" ]] && source "$APPCORE_LIBS/apt-helpers.sh"
    [[ -f "$APPCORE_LIBS/netconfig.sh" ]] && source "$APPCORE_LIBS/netconfig.sh"
fi

#===============================================================================
# UTILITIES
#
# info/yesno/die delegate to appliance-core's sized whiptail wrappers
# when the lib is loaded (auto-sizes from `tput`, capped at 24x100,
# floored at 10x60). Fallback hand-fixed dimensions preserve behavior
# on older images that don't have the lib vendored — the same pattern
# samba-addc and smb-proxy use.
#===============================================================================
die() {
    if command -v appcore_tui_msgbox >/dev/null 2>&1; then
        appcore_tui_msgbox "FATAL: $*"
    else
        whiptail --msgbox "FATAL: $*" 10 60
    fi
    exit 1
}
info() {
    if command -v appcore_tui_msgbox >/dev/null 2>&1; then
        appcore_tui_msgbox "$*"
    else
        whiptail --msgbox "$*" 12 64
    fi
}
yesno() {
    if command -v appcore_tui_yesno >/dev/null 2>&1; then
        appcore_tui_yesno "$*"
    else
        whiptail --yesno "$*" 10 60
    fi
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "ERROR: Run as root (sudo $SCRIPT_NAME)." >&2
        exit 1
    fi
}

# Idempotent loader for the persistent deploy.env state.
load_deploy() {
    # TODO: declare appliance-specific defaults here
    # REALM="" DC_HOST="" DC_IP="" ...
    if [[ -f "$DEPLOY_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$DEPLOY_FILE"
    fi
}

save_deploy() {
    mkdir -p "$STATE_DIR"
    cat > "$DEPLOY_FILE" <<EOF
# Generated by $SCRIPT_NAME. Safe to edit by hand if you know why.
# Credentials live in protected credential files (mode 0600), NOT here.
# TODO: list every persisted variable
# REALM="${REALM:-}"
# ...
EOF
    chmod 0644 "$DEPLOY_FILE"
}

#===============================================================================
# TUI
#===============================================================================
main_menu() {
    while true; do
        local choice
        choice=$(whiptail --title "$SCRIPT_NAME v$VERSION" \
            --menu "Pick an action." \
            "$WT_HEIGHT" "$WT_WIDTH" "$WT_MENU_HEIGHT" \
            "1" "TODO: appliance-specific menu entry" \
            "S" "Show status" \
            "Q" "Quit" \
            3>&1 1>&2 2>&3) || break
        case "$choice" in
            1) info "TODO" ;;
            S) cli_status | whiptail --textbox /dev/stdin 20 76 ;;
            Q) break ;;
        esac
    done
}

#===============================================================================
# HEADLESS CLI
#===============================================================================
print_help() {
    cat <<HLP
$SCRIPT_NAME v$VERSION

Usage:
  sudo $SCRIPT_NAME                    Interactive whiptail TUI.

  sudo $SCRIPT_NAME --status           Print summary, exit 0.

  sudo $SCRIPT_NAME --version

# TODO: per-action headless subcommand reference
# Pattern: see samba-addc-appliance/samba-sconfig.sh and
# smb-proxy-appliance/smbproxy-sconfig.sh for the full CLI patterns
# (--join-domain, --configure-backend, --configure-frontend,
# --apply-firewall, etc.). Use --pass-stdin for any password input
# so it doesn't appear in process listings.
HLP
}

cli_status() {
    load_deploy
    cat <<EOF
hostname:        $(hostname -f 2>/dev/null || hostname)
# TODO: appliance-specific status fields
EOF
}

main_cli() {
    case "${1:-}" in
        --help|-h)             print_help ;;
        --version|-V)          echo "$SCRIPT_NAME $VERSION" ;;
        --status)              cli_status ;;
        # TODO: per-action subcommand dispatchers
        *) echo "unknown subcommand: ${1:-}" >&2; print_help; return 2 ;;
    esac
}

#===============================================================================
# ENTRY POINT
#===============================================================================
check_root
if [[ $# -eq 0 ]]; then
    main_menu
else
    main_cli "$@"
fi
